---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | no runtime errors.'
      ansible.builtin.assert:
        quiet: true
        that:
          - 'true == true'
        fail_msg: |
          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │    Init uses all imported roles. There should never be errors.    │
          │                                                                   │
          ╰───────────────────────────────────────────────────────────────────╯
